### ISSUE TITLE
Wrongly formatted code, better way to use comparator.

### ISSUE THREAD

**Issue by r-by** [ikigaigg/xList#1]
Some of your code is randomly formatted wrongly for some reason?

https://github.com/ikigaigg/xList/blob/96527edccd9e7c689bbc31b850f5e74830dc9ace/java/gg/ikigai/list/Main.java#L19

https://github.com/ikigaigg/xList/blob/96527edccd9e7c689bbc31b850f5e74830dc9ace/java/gg/ikigai/list/command/ListCommand.java#L21

Also for your 'PriorityManager' (which is just a comparator for another object) might as-well just be removed and implement comparator<T> in your GroupHandler.

You should also consider using a 'handlers' package for multiple handlers instead of just slapping everything in a 'useful' package.

**Comment by ikigaigg** [comment]
Thanks for the tips, I am not really good with priorities and stuff.
